### ISSUE TITLE
Extract Schema without Grants

### ISSUE THREAD

**Issue by iolbr** [omniti-labs/pg_extractor#45]
Hi,

we like to generate the scripts for all schema objects of a given database but we have only a user with limited access rights to do the job. One major grant that is missing is the select grant on pg_authid. When we exucte the script with

> python pg_extractor.py -N test -x --no_owner --getall --schemadir 

we'd expect that we'll get the scripts without grants and roles. Instead we get an error:

> Error in pg_dumpall command while extracting roles: pg_dumpall: query failed: Error no access rights for relation pg_authid

Best,
Ingo

**Comment by keithf4** [comment]
You're going to need a superuser to be able to extract all the information about other roles from the database. That's why it's complaining about lack of permissions to the pg_authid table. Otherwise it's a security risk allowing limited-access roles to be able to fully query that system catalog the way that pg_dumpall requires (needs to be able to see the user's password hashes, etc).

You can try granting select access on that system catalog, but I'm not 100% sure that will even work to allow pg_dumpall to gather what it needs.

**Comment by iolbr** [comment]
Hi, thanks for the prompt reply. I'm looking for a way to turn off extracting the grants and roles. Especially the access the pg_authid table for the same reason you mentioned. We don't like the developers to fiddle with that view... But if I get you right the access violation I got is not rooted in the extractor part it is due to the og_dump call?

**Comment by keithf4** [comment]
Yes, the only ways pg_extractor actually connects to the database is through pg_dump, pg_dumpall and pg_restore. It doesn't make any other connections itself (hence not needing psycopg).

There's no single flag to just turn off extracting the roles, but if you use some of the other flags to specifically dump the items you want other than the roles, that should work. The default when not specified it `--getall`, which does include the `--getroles` option. See the `--help` for all the other `--get*` options that are available.

**Comment by iolbr** [comment]
Thanks for the support! We'll rewrite our extraction scripts and remove --getall and replace it with a tailored approach.
